# Remove this file when you are going to use this plugin as a library.
name: FishLib
version: ${project.version}
authors:
  - Lucky_fish0w0
  - Shiina_xi_yu
  - Hai_tun
  - Faint_Cloudy
main: moe.orangemc.fishlib.FishLibraryPlugin
api-version: 1.18
description: A library used by Lucky_fish0w0

libraries:
  - "org.apache.commons:commons-lang3:3.12.0"
  - "commons-io:commons-io:2.11.0"
  - "org.apache.commons:commons-imaging:1.0-alpha2"
